/********************************************************************
* rootIO_Classes.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootIO_Classes.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablerootIO_Classes();
extern void G__cpp_setup_inheritancerootIO_Classes();
extern void G__cpp_setup_typetablerootIO_Classes();
extern void G__cpp_setup_memvarrootIO_Classes();
extern void G__cpp_setup_globalrootIO_Classes();
extern void G__cpp_setup_memfuncrootIO_Classes();
extern void G__cpp_setup_funcrootIO_Classes();
extern void G__set_cpp_environmentrootIO_Classes();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/afs/cern.ch/user/t/tprzedzi/HepMC3/rootIO/include/rootIO_Classes.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__rootIO_ClassesLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__rootIO_ClassesLN_string;
extern G__linked_taginfo G__rootIO_ClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__rootIO_ClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootIO_ClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__rootIO_ClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootIO_ClassesLN_HepMC;
extern G__linked_taginfo G__rootIO_ClassesLN_HepMCcLcLSetup;
extern G__linked_taginfo G__rootIO_ClassesLN_HepMCcLcLFourVector;
extern G__linked_taginfo G__rootIO_ClassesLN_HepMCcLcLGenParticleData;
extern G__linked_taginfo G__rootIO_ClassesLN_HepMCcLcLGenVertexData;
extern G__linked_taginfo G__rootIO_ClassesLN_HepMCcLcLUnits;
extern G__linked_taginfo G__rootIO_ClassesLN_HepMCcLcLUnitscLcLMomentumUnit;
extern G__linked_taginfo G__rootIO_ClassesLN_HepMCcLcLUnitscLcLLengthUnit;
extern G__linked_taginfo G__rootIO_ClassesLN_HepMCcLcLGenPdfInfo;
extern G__linked_taginfo G__rootIO_ClassesLN_HepMCcLcLGenHeavyIon;
extern G__linked_taginfo G__rootIO_ClassesLN_HepMCcLcLGenCrossSection;
extern G__linked_taginfo G__rootIO_ClassesLN_HepMCcLcLGenEventData;
extern G__linked_taginfo G__rootIO_ClassesLN_vectorlEHepMCcLcLGenParticleDatacOallocatorlEHepMCcLcLGenParticleDatagRsPgR;
extern G__linked_taginfo G__rootIO_ClassesLN_vectorlEHepMCcLcLGenParticleDatacOallocatorlEHepMCcLcLGenParticleDatagRsPgRcLcLiterator;
extern G__linked_taginfo G__rootIO_ClassesLN_reverse_iteratorlEvectorlEHepMCcLcLGenParticleDatacOallocatorlEHepMCcLcLGenParticleDatagRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootIO_ClassesLN_vectorlEHepMCcLcLGenVertexDatacOallocatorlEHepMCcLcLGenVertexDatagRsPgR;
extern G__linked_taginfo G__rootIO_ClassesLN_vectorlEHepMCcLcLGenVertexDatacOallocatorlEHepMCcLcLGenVertexDatagRsPgRcLcLiterator;
extern G__linked_taginfo G__rootIO_ClassesLN_reverse_iteratorlEvectorlEHepMCcLcLGenVertexDatacOallocatorlEHepMCcLcLGenVertexDatagRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootIO_ClassesLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__rootIO_ClassesLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator;
extern G__linked_taginfo G__rootIO_ClassesLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<HepMC::GenParticleData,allocator<HepMC::GenParticleData> > G__vectorlEHepMCcLcLGenParticleDatacOallocatorlEHepMCcLcLGenParticleDatagRsPgR;
typedef vector<HepMC::GenVertexData,allocator<HepMC::GenVertexData> > G__vectorlEHepMCcLcLGenVertexDatacOallocatorlEHepMCcLcLGenVertexDatagRsPgR;
typedef vector<int,allocator<int> > G__vectorlEintcOallocatorlEintgRsPgR;
