# - Locate Photospp library
# Defines:
#
#  PHOTOSHEPMC2_FOUND
#  PHOTOSHEPMC2_VERSION
#  PHOTOSHEPMC2_INCLUDE_DIR
#  PHOTOSHEPMC2_INCLUDE_DIRS (not cached)
#  PHOTOSHEPMC2_LIBRARY
#  PHOTOSHEPMC2_LIBRARIES (not cached) : includes libraries

find_path(PHOTOSHEPMC2_INCLUDE_DIR Photos.h
  HINTS $ENV{PHOTOSHEPMC2_ROOT_DIR}/include ${PHOTOSHEPMC2_ROOT_DIR}/include)

if(PHOTOSHEPMC2_INCLUDE_DIR)
  find_library(PHOTOSHEPMC2_LIBRARY NAMES PhotosCxxInterface
    HINTS $ENV{PHOTOSHEPMC2_ROOT_DIR}/lib ${PHOTOSHEPMC2_ROOT_DIR}/lib)

  set(PHOTOSHEPMC2_INCLUDE_DIRS ${PHOTOSHEPMC2_INCLUDE_DIR})
  set(PHOTOSHEPMC2_LIBRARIES ${PHOTOSHEPMC2_LIBRARY})
endif()

# handle the QUIETLY and REQUIRED arguments and set PHOTOSHEPMC2_FOUND to TRUE if
# all listed variables are TRUE

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Photos DEFAULT_MSG PHOTOSHEPMC2_INCLUDE_DIR PHOTOSHEPMC2_LIBRARY)

mark_as_advanced(PHOTOSHEPMC2_FOUND PHOTOSHEPMC2_INCLUDE_DIR PHOTOSHEPMC2_LIBRARY)

